"""New authored reference problems; inputs are assumptions, never part ratings.

Each recipe is an indivisible family before parameters or boards are rendered.
These are reference projects, not collected customer projects or measurements.
"""
import math

# family: domain, project, question, derivation, output unit, three parameter sets
RECIPES = {
    "weighted-summer": ("analog", "two-channel mixer", "For an ideal op-amp summing node at 0 V, calculate the output. Rf, R1 and R2 are in ohm; V1 and V2 in V. The supplied output rails are -12 and +12 V.", "KCL gives Vout = -Rf*(V1/R1 + V2/R2); the computed voltage must remain within the supplied rails.", "V", [dict(rf=10000, r1=20000, r2=40000, v1=2, v2=4), dict(rf=22000, r1=33000, r2=47000, v1=1.2, v2=-0.8), dict(rf=4700, r1=10000, r2=22000, v1=-2, v2=3)]),
    "sensor-bridge": ("analog", "balanced sensor bridge", "Two unloaded resistor branches share a supplied excitation V. Each branch has top and bottom resistors in ohm. Calculate left midpoint minus right midpoint voltage.", "Each midpoint follows its bottom resistor fraction of excitation; subtract the right voltage from the left. This ideal unloaded bridge model excludes sensor tolerances.", "V", [dict(v=5, lt=1000, lb=1100, rt=1000, rb=1000), dict(v=3.3, lt=2200, lb=2100, rt=2200, rb=2300), dict(v=2.5, lt=4700, lb=4700, rt=4700, rb=4800)]),
    "capacitor-decay": ("analog", "hold capacitor discharge", "An ideal capacitor discharges through a resistor. R is in ohm, C in F, initial and threshold voltages in V. Find seconds until the threshold is reached, neglecting all other leakage.", "The voltage follows V0*exp(-t/(R*C)); solve t=R*C*ln(V0/Vthreshold). Both voltages must be positive and the threshold below the initial voltage.", "s", [dict(r=10000, c=0.000001, v0=5, vt=1), dict(r=47000, c=0.0000022, v0=3.3, vt=0.7), dict(r=2200, c=0.00001, v0=12, vt=2)]),
    "even-parity": ("digital", "telemetry parity encoder", "A supplied unsigned 8-bit payload needs an even-parity bit. Return 0 or 1 so payload plus parity contains an even number of ones.", "The parity bit is the payload population count modulo two; adding it makes the count even.", "bit", [dict(payload=173), dict(payload=254), dict(payload=128)]),
    "signed-saturation": ("digital", "audio accumulator limiter", "Add two supplied signed 16-bit integer samples with saturation to [-32768,32767]. Return the stored integer code; wraparound is forbidden.", "Add in a wider accumulator, then clamp between the signed 16-bit limits before storage.", "code", [dict(a=30000, b=10000), dict(a=-30000, b=-9000), dict(a=15000, b=-10000)]),
    "rollover-elapsed": ("timing", "uptime event age", "The supplied now and then values are uint32 millisecond counters. Actual elapsed time is known to be below one full wrap. Find elapsed milliseconds across possible rollover.", "Unsigned subtraction modulo 2^32 yields elapsed milliseconds when the interval is shorter than one wrap. It cannot recover multiple wraps.", "ms", [dict(now=20, then=4294967280), dict(now=1000, then=750), dict(now=3, then=4294967295)]),
    "scheduler-load": ("timing", "periodic task capacity", "Supplied task execution budgets C1,C2 and periods T1,T2 are in ms. Find total processor utilization as a fraction. This is a load estimate, not a schedulability or deadline proof.", "Average demand is C1/T1+C2/T2. Interrupt overhead and blocking are excluded from these supplied budgets.", "fraction", [dict(c1=2, t1=10, c2=3, t2=20), dict(c1=1, t1=5, c2=4, t2=25), dict(c1=3, t1=12, c2=2, t2=18)]),
    "uart-frame-time": ("buses", "serial capture buffer", "Send N bytes with one start bit, D data bits, P parity bits and S stop bits per frame at the supplied baud. Find ideal wire time in seconds, excluding idle gaps.", "There are N*(1+D+P+S) serial bits; divide by baud in bits/s. Buffering latency is outside this ideal wire-time calculation.", "s", [dict(n=40, d=8, p=0, s=1, baud=9600), dict(n=63, d=7, p=1, s=2, baud=19200), dict(n=120, d=8, p=1, s=1, baud=115200)]),
    "i2c-clock-budget": ("buses", "register transaction budget", "An ideal I2C write sends one address byte and N payload bytes at the supplied clock rate Hz. Count nine clocks per byte including ACK. Find clocked time in seconds; exclude START/STOP timing, arbitration and stretching.", "Clock demand is 9*(1+N), divided by the supplied clock frequency. This is not an end-to-end transaction latency guarantee.", "s", [dict(n=2, hz=100000), dict(n=16, hz=400000), dict(n=7, hz=100000)]),
    "linear-regulator-loss": ("power", "bench supply heat estimate", "For a hypothetical linear regulator with input/output V and load current A, calculate dissipated W. Ignore quiescent current. Values are supplied operating assumptions, not approved component limits.", "Input power minus load power gives heat: (Vin-Vout)*I. Junction temperature still requires the exact part, thermal path and ambient conditions.", "W", [dict(vin=9, vout=5, i=0.12), dict(vin=5, vout=3.3, i=0.25), dict(vin=12, vout=5, i=0.08)]),
    "ideal-buck-ripple": ("power", "inductor ripple estimate", "For an ideal continuous-conduction buck, supplied Vin/Vout are V, L is H and switching frequency Hz. Calculate peak-to-peak inductor current A. Ideal duty ratio is Vout/Vin; parasitics and ratings are excluded.", "During on-time, inductor slope is (Vin-Vout)/L and on-time is (Vout/Vin)/f. Their product is peak-to-peak ripple; off-time must give the same magnitude.", "A", [dict(vin=12, vout=5, l=0.0001, hz=100000), dict(vin=24, vout=12, l=0.00022, hz=200000), dict(vin=9, vout=3.3, l=0.000047, hz=400000)]),
    "ideal-adc-bin": ("adc", "quantizer reference model", "Use the explicitly defined ideal unsigned FLOOR-bin quantizer code=floor(Vin*2^N/Vref). N is bits; voltages are V; 0<=Vin<Vref. Return integer code. This mathematical model is not a physical ADC transfer-function claim.", "The model has 2^N equal-width bins. Select the bin whose lower boundary includes Vin and whose upper boundary excludes it; physical ADC offset/gain and endpoint conventions need its datasheet.", "code", [dict(bits=10, vin=1.1, vref=3.3), dict(bits=12, vin=2.0, vref=5), dict(bits=8, vin=0, vref=2.5)]),
    "uncorrelated-average": ("adc", "noise averaging estimate", "N independent zero-mean samples each have supplied RMS noise sigma in V. Find RMS noise of their arithmetic mean. Noise is uncorrelated and stationary; correlated drift is excluded.", "Variances add for independent samples. Division by N in the mean scales variance by N squared, leaving sigma/sqrt(N) RMS noise.", "V-rms", [dict(n=16, sigma=0.008), dict(n=25, sigma=0.015), dict(n=64, sigma=0.024)]),
    "hysteresis-state": ("control", "thermostat state transition", "A heating controller turns ON at x<=low, OFF at x>=high, and otherwise retains supplied previous state 0/1. Temperatures are degrees C and low<high. Return next state for one sample.", "Apply the two inclusive thresholds first. Inside the dead band, preserve the prior state; this suppresses chatter near one threshold.", "state", [dict(x=19, low=20, high=24, previous=0), dict(x=22, low=20, high=24, previous=1), dict(x=25, low=20, high=24, previous=1)]),
    "proportional-clamp": ("control", "bounded actuator demand", "For a supplied dimensionless error and positive gain, compute demand clipped to [0,1]. This is a static proportional controller without integral or derivative action.", "Multiply gain by error; project the result onto the actuator interval [0,1]. This calculation alone makes no stability claim.", "fraction", [dict(gain=0.2, error=3), dict(gain=0.5, error=-2), dict(gain=0.4, error=4)]),
    "ring-occupancy": ("memory", "serial queue occupancy", "An N-slot ring uses head as next write and tail as next read, reserving one empty slot to distinguish full from empty. Supplied indices lie in [0,N). Find occupied slots; N is a power of two.", "Occupancy is (head-tail) modulo N. With the reserved slot, maximum usable capacity is N-1; equal indices mean empty.", "slots", [dict(n=16, head=2, tail=13), dict(n=32, head=20, tail=4), dict(n=8, head=3, tail=3)]),
    "buffer-budget": ("memory", "double-buffer memory plan", "Allocate two buffers each with N records of supplied width W bytes, plus M metadata bytes. Find total bytes. Width includes all padding; stack, heap allocator overhead and other objects are excluded.", "Two arrays consume 2*N*W bytes and metadata consumes M. Compare this subtotal with an exact target's available memory only after accounting for all other allocations.", "bytes", [dict(n=40, w=6, m=16), dict(n=64, w=4, m=24), dict(n=120, w=3, m=32)]),
}


def answer(family, p):
    if family == "weighted-summer": return -p["rf"] * (p["v1"] / p["r1"] + p["v2"] / p["r2"])
    if family == "sensor-bridge": return p["v"] * (p["lb"] / (p["lt"] + p["lb"]) - p["rb"] / (p["rt"] + p["rb"]))
    if family == "capacitor-decay": return p["r"] * p["c"] * math.log(p["v0"] / p["vt"])
    if family == "even-parity": return p["payload"].bit_count() % 2
    if family == "signed-saturation": return max(-32768, min(32767, p["a"] + p["b"]))
    if family == "rollover-elapsed": return (p["now"] - p["then"]) % (1 << 32)
    if family == "scheduler-load": return p["c1"] / p["t1"] + p["c2"] / p["t2"]
    if family == "uart-frame-time": return p["n"] * (1 + p["d"] + p["p"] + p["s"]) / p["baud"]
    if family == "i2c-clock-budget": return 9 * (1 + p["n"]) / p["hz"]
    if family == "linear-regulator-loss": return (p["vin"] - p["vout"]) * p["i"]
    if family == "ideal-buck-ripple": return (p["vin"] - p["vout"]) * p["vout"] / (p["vin"] * p["l"] * p["hz"])
    if family == "ideal-adc-bin": return math.floor(p["vin"] * (1 << p["bits"]) / p["vref"])
    if family == "uncorrelated-average": return p["sigma"] / math.sqrt(p["n"])
    if family == "hysteresis-state": return 1 if p["x"] <= p["low"] else 0 if p["x"] >= p["high"] else p["previous"]
    if family == "proportional-clamp": return max(0, min(1, p["gain"] * p["error"]))
    if family == "ring-occupancy": return (p["head"] - p["tail"]) & (p["n"] - 1)
    if family == "buffer-budget": return 2 * p["n"] * p["w"] + p["m"]
    raise ValueError("Unknown recipe")
