"""
PCB design rule checking for VoltForge manufacturing exports.

The engine validates the PCB-domain layout generated by the UI. It deliberately
works on generic dictionaries so the FastAPI route can accept project snapshots
without coupling to a frontend build artifact.
"""

from __future__ import annotations

import logging
import math
from typing import Any, Dict, Iterable, List, Optional, Tuple

logger = logging.getLogger("voltforge-ai.drc_engine")

Point = Tuple[float, float]
Segment = Tuple[Point, Point]


class PcbDrcEngine:
    MIN_TRACE_WIDTH_MM = 0.1524  # 6 mil
    MIN_CLEARANCE_MM = 0.1524  # 6 mil
    MIN_DRILL_MM = 0.2
    MIN_ANNULAR_RING_MM = 0.15

    @classmethod
    def run_drc(
        cls,
        board_width_mm: float,
        board_height_mm: float,
        footprints: List[Dict[str, Any]],
        traces: List[Dict[str, Any]],
        vias: List[Dict[str, Any]],
        wires: Optional[List[Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        violations: List[Dict[str, Any]] = []
        wires = wires or []

        cls._check_board_size(board_width_mm, board_height_mm, violations)
        cls._check_trace_rules(board_width_mm, board_height_mm, traces, violations)
        cls._check_footprint_rules(board_width_mm, board_height_mm, footprints, violations)
        cls._check_via_rules(board_width_mm, board_height_mm, vias, violations)
        cls._check_clearances(footprints, traces, vias, violations)
        cls._check_unrouted_nets(wires, traces, violations)

        errors = sum(1 for item in violations if item["severity"] == "ERROR")
        warnings = sum(1 for item in violations if item["severity"] == "WARNING")

        return {
            "passed": errors == 0,
            "totalViolations": len(violations),
            "errors": errors,
            "warnings": warnings,
            "violations": violations,
            "rulesChecked": [
                "Minimum Trace Width (6 mil)",
                "Minimum Copper Clearance (6 mil)",
                "Minimum Drill Hole (0.2 mm)",
                "Annular Ring Width (6 mil)",
                "Board Outline Keepout",
                "Unrouted Net Completeness",
            ],
        }

    @classmethod
    def _check_board_size(
        cls,
        board_width_mm: float,
        board_height_mm: float,
        violations: List[Dict[str, Any]],
    ) -> None:
        if board_width_mm <= 0 or board_height_mm <= 0:
            violations.append({
                "id": "drc_board_size",
                "severity": "ERROR",
                "rule": "Board Dimensions",
                "message": "Board width and height must be positive millimeter values.",
            })

    @classmethod
    def _check_trace_rules(
        cls,
        board_width_mm: float,
        board_height_mm: float,
        traces: List[Dict[str, Any]],
        violations: List[Dict[str, Any]],
    ) -> None:
        for index, trace in enumerate(traces):
            width = cls._float(trace.get("width_mm"), 0.254)
            layer = str(trace.get("layer", "F.Cu"))
            if width < cls.MIN_TRACE_WIDTH_MM:
                violations.append({
                    "id": f"drc_trace_width_{index}",
                    "severity": "ERROR",
                    "rule": "Minimum Trace Width",
                    "message": f"Trace on {layer} is {cls._mm_to_mil(width):.1f} mil (< 6 mil manufacturer limit).",
                    "layer": layer,
                })

            for point_index, point in enumerate(cls._points(trace.get("points", []))):
                if not cls._inside_board(point, board_width_mm, board_height_mm):
                    violations.append({
                        "id": f"drc_trace_bounds_{index}_{point_index}",
                        "severity": "ERROR",
                        "rule": "Board Outline Boundary",
                        "message": f"Trace point on {layer} lies outside the board outline.",
                        "x": point[0],
                        "y": point[1],
                    })

    @classmethod
    def _check_footprint_rules(
        cls,
        board_width_mm: float,
        board_height_mm: float,
        footprints: List[Dict[str, Any]],
        violations: List[Dict[str, Any]],
    ) -> None:
        for footprint in footprints:
            name = str(footprint.get("name", footprint.get("id", "Component")))
            x = cls._float(footprint.get("x"), 0)
            y = cls._float(footprint.get("y"), 0)
            width = cls._float(footprint.get("width"), 10)
            height = cls._float(footprint.get("height"), 10)

            rotation = math.radians(cls._float(footprint.get("rotation"), 0))
            rotated_width = abs(width * math.cos(rotation)) + abs(height * math.sin(rotation))
            rotated_height = abs(width * math.sin(rotation)) + abs(height * math.cos(rotation))
            if (
                x - rotated_width / 2 < 0
                or x + rotated_width / 2 > board_width_mm
                or y - rotated_height / 2 < 0
                or y + rotated_height / 2 > board_height_mm
            ):
                violations.append({
                    "id": f"drc_footprint_bounds_{footprint.get('id', name)}",
                    "severity": "ERROR",
                    "rule": "Board Outline Boundary",
                    "message": f"Component '{name}' extends beyond the {board_width_mm}x{board_height_mm}mm board edge.",
                    "x": x,
                    "y": y,
                })

            for pad in footprint.get("pads", []):
                pad_center = cls._pad_center(footprint, pad)
                pad_radius = max(cls._float(pad.get("width"), 1), cls._float(pad.get("height"), 1)) / 2
                if not cls._inside_board(pad_center, board_width_mm, board_height_mm, pad_radius):
                    violations.append({
                        "id": f"drc_pad_bounds_{footprint.get('id', name)}_{pad.get('id', 'pad')}",
                        "severity": "ERROR",
                        "rule": "Board Outline Boundary",
                        "message": f"Pad '{pad.get('name', pad.get('id', 'pad'))}' on '{name}' violates board edge keepout.",
                        "x": pad_center[0],
                        "y": pad_center[1],
                    })

    @classmethod
    def _check_via_rules(
        cls,
        board_width_mm: float,
        board_height_mm: float,
        vias: List[Dict[str, Any]],
        violations: List[Dict[str, Any]],
    ) -> None:
        for index, via in enumerate(vias):
            drill = cls._float(via.get("drill_mm"), 0.3)
            pad = cls._float(via.get("pad_mm"), 0.6)
            center = (cls._float(via.get("x"), 0), cls._float(via.get("y"), 0))

            if drill < cls.MIN_DRILL_MM:
                violations.append({
                    "id": f"drc_drill_{index}",
                    "severity": "ERROR",
                    "rule": "Minimum Drill Size",
                    "message": f"Via drill diameter {drill:.3f}mm is below manufacturer minimum ({cls.MIN_DRILL_MM}mm).",
                    "x": center[0],
                    "y": center[1],
                })

            annular_ring = (pad - drill) / 2
            if annular_ring < cls.MIN_ANNULAR_RING_MM:
                violations.append({
                    "id": f"drc_annular_{index}",
                    "severity": "WARNING",
                    "rule": "Annular Ring Width",
                    "message": f"Via annular ring ({annular_ring:.3f}mm) is below recommended 0.15mm.",
                    "x": center[0],
                    "y": center[1],
                })

            if not cls._inside_board(center, board_width_mm, board_height_mm, pad / 2):
                violations.append({
                    "id": f"drc_via_bounds_{index}",
                    "severity": "ERROR",
                    "rule": "Board Outline Boundary",
                    "message": "Via pad violates board edge keepout.",
                    "x": center[0],
                    "y": center[1],
                })

    @classmethod
    def _check_clearances(
        cls,
        footprints: List[Dict[str, Any]],
        traces: List[Dict[str, Any]],
        vias: List[Dict[str, Any]],
        violations: List[Dict[str, Any]],
    ) -> None:
        copper_items = []

        for trace_index, trace in enumerate(traces):
            points = cls._points(trace.get("points", []))
            for seg_index, segment in enumerate(cls._segments(points)):
                copper_items.append({
                    "id": f"trace_{trace_index}_{seg_index}",
                    "kind": "trace",
                    "layer": trace.get("layer", "F.Cu"),
                    "net": trace.get("netId"),
                    "segment": segment,
                    "radius": cls._float(trace.get("width_mm"), 0.254) / 2,
                })

        for footprint in footprints:
            fx = cls._float(footprint.get("x"), 0)
            fy = cls._float(footprint.get("y"), 0)
            for pad in footprint.get("pads", []):
                copper_items.append({
                    "id": f"pad_{footprint.get('id', 'fp')}_{pad.get('id', 'pad')}",
                    "kind": "pad",
                    "layer": pad.get("layer", "F.Cu"),
                    "net": pad.get("netId"),
                    "point": cls._pad_center(footprint, pad),
                    "radius": max(cls._float(pad.get("width"), 1), cls._float(pad.get("height"), 1)) / 2,
                })

        for via_index, via in enumerate(vias):
            copper_items.append({
                "id": f"via_{via_index}",
                "kind": "via",
                "layer": "ALL",
                "net": via.get("netId"),
                "point": (cls._float(via.get("x"), 0), cls._float(via.get("y"), 0)),
                "radius": cls._float(via.get("pad_mm"), 0.6) / 2,
            })

        for left_index, left in enumerate(copper_items):
            for right in copper_items[left_index + 1:]:
                if cls._same_net(left.get("net"), right.get("net")):
                    continue
                if not cls._same_copper_layer(left.get("layer"), right.get("layer")):
                    continue

                clearance = cls._copper_clearance(left, right)
                if clearance < cls.MIN_CLEARANCE_MM:
                    violations.append({
                        "id": f"drc_clearance_{left['id']}_{right['id']}",
                        "severity": "ERROR",
                        "rule": "Minimum Copper Clearance",
                        "message": f"Copper clearance is {cls._mm_to_mil(max(clearance, 0)):.1f} mil (< 6 mil) between {left['kind']} and {right['kind']}.",
                    })

    @classmethod
    def _check_unrouted_nets(
        cls,
        wires: List[Dict[str, Any]],
        traces: List[Dict[str, Any]],
        violations: List[Dict[str, Any]],
    ) -> None:
        if len(wires) > len(traces):
            violations.append({
                "id": "drc_unrouted_nets",
                "severity": "WARNING",
                "rule": "Unrouted Net Connections",
                "message": f"{len(wires) - len(traces)} schematic net connection(s) do not have corresponding routed copper traces.",
            })

    @staticmethod
    def _float(value: Any, default: float) -> float:
        try:
            return float(value)
        except (TypeError, ValueError):
            return default

    @staticmethod
    def _mm_to_mil(value_mm: float) -> float:
        return value_mm / 0.0254

    @staticmethod
    def _inside_board(point: Point, width: float, height: float, margin: float = 0) -> bool:
        return margin <= point[0] <= width - margin and margin <= point[1] <= height - margin

    @classmethod
    def _points(cls, raw_points: Iterable[Dict[str, Any]]) -> List[Point]:
        return [
            (cls._float(point.get("x"), 0), cls._float(point.get("y"), 0))
            for point in raw_points
        ]

    @classmethod
    def _pad_center(cls, footprint: Dict[str, Any], pad: Dict[str, Any]) -> Point:
        fx = cls._float(footprint.get("x"), 0)
        fy = cls._float(footprint.get("y"), 0)
        px = cls._float(pad.get("x"), 0)
        py = cls._float(pad.get("y"), 0)
        angle = math.radians(cls._float(footprint.get("rotation"), 0))
        return (
            fx + px * math.cos(angle) - py * math.sin(angle),
            fy + px * math.sin(angle) + py * math.cos(angle),
        )

    @staticmethod
    def _segments(points: List[Point]) -> List[Segment]:
        return list(zip(points, points[1:]))

    @staticmethod
    def _same_net(left: Any, right: Any) -> bool:
        return bool(left) and bool(right) and str(left) == str(right)

    @staticmethod
    def _same_copper_layer(left: Any, right: Any) -> bool:
        return left == "ALL" or right == "ALL" or left == right

    @classmethod
    def _copper_clearance(cls, left: Dict[str, Any], right: Dict[str, Any]) -> float:
        if "segment" in left and "segment" in right:
            distance = cls._segment_distance(left["segment"], right["segment"])
        elif "segment" in left:
            distance = cls._point_segment_distance(right["point"], left["segment"])
        elif "segment" in right:
            distance = cls._point_segment_distance(left["point"], right["segment"])
        else:
            distance = math.dist(left["point"], right["point"])
        return distance - cls._float(left.get("radius"), 0) - cls._float(right.get("radius"), 0)

    @classmethod
    def _segment_distance(cls, left: Segment, right: Segment) -> float:
        if cls._segments_intersect(left, right):
            return 0.0
        return min(
            cls._point_segment_distance(left[0], right),
            cls._point_segment_distance(left[1], right),
            cls._point_segment_distance(right[0], left),
            cls._point_segment_distance(right[1], left),
        )

    @staticmethod
    def _point_segment_distance(point: Point, segment: Segment) -> float:
        (x1, y1), (x2, y2) = segment
        dx = x2 - x1
        dy = y2 - y1
        if dx == 0 and dy == 0:
            return math.dist(point, segment[0])
        t = max(0.0, min(1.0, ((point[0] - x1) * dx + (point[1] - y1) * dy) / (dx * dx + dy * dy)))
        projected = (x1 + t * dx, y1 + t * dy)
        return math.dist(point, projected)

    @staticmethod
    def _segments_intersect(left: Segment, right: Segment) -> bool:
        def orient(a: Point, b: Point, c: Point) -> float:
            return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])

        def on_segment(a: Point, b: Point, c: Point) -> bool:
            return (
                min(a[0], c[0]) <= b[0] <= max(a[0], c[0])
                and min(a[1], c[1]) <= b[1] <= max(a[1], c[1])
            )

        p1, p2 = left
        q1, q2 = right
        o1 = orient(p1, p2, q1)
        o2 = orient(p1, p2, q2)
        o3 = orient(q1, q2, p1)
        o4 = orient(q1, q2, p2)

        if o1 * o2 < 0 and o3 * o4 < 0:
            return True
        eps = 1e-9
        return (
            abs(o1) < eps and on_segment(p1, q1, p2)
            or abs(o2) < eps and on_segment(p1, q2, p2)
            or abs(o3) < eps and on_segment(q1, p1, q2)
            or abs(o4) < eps and on_segment(q1, p2, q2)
        )
