"""
Voltforge AI - SPICE Netlist & Analog Circuit Simulation Engine
Covers Features 101-110: DC Operating Point, Transient Analysis, AC Response,
Modified Nodal Analysis (MNA), LED I-V curves, PWM Integration, Power Loss Analysis.
"""

import math
import logging
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("voltforge-ai.spice")


class SpiceNetlistExporter:
    """Converts Voltforge canvas components and wires into standard SPICE (.cir) netlists."""

    COMPONENT_SPICE_MAP = {
        "RESISTOR": "R",
        "CAPACITOR": "C",
        "INDUCTOR": "L",
        "LED": "D",
        "DIODE": "D",
        "NPN_TRANSISTOR": "Q",
        "PNP_TRANSISTOR": "Q",
        "NMOS": "M",
        "PMOS": "M",
    }

    @classmethod
    def _legacy_export_netlist(
        cls,
        components: List[Dict[str, Any]],
        wires: List[Dict[str, Any]],
        board_type: str = "ARDUINO_UNO",
        v_supply: float = 5.0,
    ) -> str:
        lines = [
            f"* Voltforge SPICE Netlist — {board_type}",
            f"* Auto-generated by Voltforge AI SPICE Engine",
            f"",
            f"Vsupply VCC 0 DC {v_supply}",
        ]

        node_counter = 1
        for idx, comp in enumerate(components):
            ctype = comp.get("type", "").upper()
            cname = comp.get("name", f"comp{idx}")
            value = comp.get("value", "1k")
            prefix = cls.COMPONENT_SPICE_MAP.get(ctype, "X")
            spice_name = f"{prefix}{idx + 1}"

            if ctype == "RESISTOR":
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} {value}")
                node_counter += 2
            elif ctype == "CAPACITOR":
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} {value}")
                node_counter += 2
            elif ctype in ("LED", "DIODE"):
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} DLED")
                node_counter += 2
            elif ctype in ("NPN_TRANSISTOR",):
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} N{node_counter + 2} Q2N2222")
                node_counter += 3
            else:
                lines.append(f"* Unknown component: {cname} ({ctype})")

        lines.append("")
        lines.append(".model DLED D(IS=1e-20 N=1.8 RS=5 BV=5)")
        lines.append(".model Q2N2222 NPN(BF=200 IS=1e-14)")
        lines.append("")
        lines.append(".op")
        lines.append(".end")

        return "\n".join(lines)


    @classmethod
    def export_netlist(
        cls,
        components: List[Dict[str, Any]],
        wires: List[Dict[str, Any]],
        board_type: str = "ARDUINO_UNO",
        v_supply: float = 5.0,
    ) -> str:
        """Export the actual canvas topology as a SPICE netlist.

        Canvas wires join ``nodeId:pinId`` endpoints.  The previous exporter
        assigned fresh nodes to every component, so a backend simulation could
        never represent the circuit the user drew.  This exporter unions those
        endpoints first and only then emits device lines.
        """
        def flatten_hierarchy(
            source_components: List[Dict[str, Any]],
            source_wires: List[Dict[str, Any]],
        ) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
            flat_components = list(source_components)
            flat_wires = list(source_wires)

            while True:
                compound = next(
                    (
                        component for component in flat_components
                        if str(component.get("type", "")).upper() == "SUB_CIRCUIT"
                    ),
                    None,
                )
                if compound is None:
                    return flat_components, flat_wires

                definition = compound.get("subCircuitDef") or (compound.get("properties") or {}).get("subCircuitDef") or {}
                internal_components = list(definition.get("internalNodes") or definition.get("components") or [])
                internal_wires = list(definition.get("internalWires") or definition.get("wires") or [])
                connections = definition.get("exposedConnections") or {}
                compound_id = str(compound.get("id", compound.get("name", "subcircuit")))

                def replace_endpoint(node_id: Any, pin_id: Any) -> Tuple[str, str]:
                    if str(node_id) != compound_id:
                        return str(node_id), str(pin_id)
                    connection = connections.get(str(pin_id)) or {}
                    return str(connection.get("nodeId", node_id)), str(connection.get("pinId", pin_id))

                external_wires = [
                    wire for wire in flat_wires
                    if str(wire.get("fromNodeId", "")) == compound_id
                    or str(wire.get("toNodeId", "")) == compound_id
                ]
                flat_wires = [
                    wire for wire in flat_wires
                    if str(wire.get("fromNodeId", "")) != compound_id
                    and str(wire.get("toNodeId", "")) != compound_id
                ]
                flat_wires.extend(internal_wires)
                for wire in external_wires:
                    rewritten = dict(wire)
                    from_node, from_pin = replace_endpoint(
                        wire.get("fromNodeId", wire.get("fromComponentId", "")),
                        wire.get("fromPinId", wire.get("fromPin", "0")),
                    )
                    to_node, to_pin = replace_endpoint(
                        wire.get("toNodeId", wire.get("toComponentId", "")),
                        wire.get("toPinId", wire.get("toPin", "0")),
                    )
                    rewritten.update({
                        "fromNodeId": from_node,
                        "fromPinId": from_pin,
                        "toNodeId": to_node,
                        "toPinId": to_pin,
                    })
                    flat_wires.append(rewritten)

                flat_components = [component for component in flat_components if component is not compound]
                flat_components.extend(internal_components)

        components, wires = flatten_hierarchy(components, wires)
        parent: Dict[str, str] = {}

        def find(key: str) -> str:
            parent.setdefault(key, key)
            if parent[key] != key:
                parent[key] = find(parent[key])
            return parent[key]

        def union(left: str, right: str) -> None:
            a, b = find(left), find(right)
            if a != b:
                parent[b] = a

        def component_id(component: Dict[str, Any]) -> str:
            return str(component.get("id", component.get("name", "component")))

        def pin_ids(component: Dict[str, Any]) -> List[str]:
            result = []
            for index, pin in enumerate(component.get("pins") or []):
                result.append(str(pin.get("id", index)) if isinstance(pin, dict) else str(pin))
            return result

        def pin_key(component: Dict[str, Any], pin_id: str) -> str:
            return f"{component_id(component)}:{pin_id}"

        for component in components:
            for pin_id in pin_ids(component):
                find(pin_key(component, pin_id))

        for wire in wires:
            from_node = str(wire.get("fromNodeId", wire.get("fromComponentId", "")))
            to_node = str(wire.get("toNodeId", wire.get("toComponentId", "")))
            from_pin = str(wire.get("fromPinId", wire.get("fromPin", "0")))
            to_pin = str(wire.get("toPinId", wire.get("toPin", "0")))
            if from_node and to_node:
                union(f"{from_node}:{from_pin}", f"{to_node}:{to_pin}")

        ground_roots = set()
        for component in components:
            ctype = str(component.get("type", "")).upper()
            for pin in component.get("pins") or []:
                if not isinstance(pin, dict):
                    continue
                label = f"{pin.get('id', '')} {pin.get('name', '')} {pin.get('type', '')}".lower()
                if ctype == "GROUND" or "ground" in label or "gnd" in label:
                    ground_roots.add(find(pin_key(component, str(pin.get("id", "")))))

        root_to_node: Dict[str, str] = {}
        next_node = 1

        def resolve_pin(component: Dict[str, Any], aliases: Tuple[str, ...], fallback_index: int = 0) -> str:
            for pin in component.get("pins") or []:
                pin_id = str(pin.get("id", "")) if isinstance(pin, dict) else str(pin)
                pin_name = str(pin.get("name", "")) if isinstance(pin, dict) else pin_id
                candidate = f"{pin_id} {pin_name}".lower().replace("_", "")
                if any(alias.lower().replace("_", "") in candidate for alias in aliases):
                    return pin_id
            ids = pin_ids(component)
            return ids[min(fallback_index, len(ids) - 1)] if ids else str(fallback_index)

        def node_for(component: Dict[str, Any], aliases: Tuple[str, ...], fallback_index: int = 0) -> str:
            nonlocal next_node
            root = find(pin_key(component, resolve_pin(component, aliases, fallback_index)))
            if root in ground_roots or str(component.get("type", "")).upper() == "GROUND":
                return "0"
            if root not in root_to_node:
                root_to_node[root] = f"N{next_node}"
                next_node += 1
            return root_to_node[root]

        def prop(component: Dict[str, Any], *names: str, default: Any = None) -> Any:
            properties = component.get("properties") or {}
            for name in names:
                if properties.get(name) is not None:
                    return properties[name]
                if component.get(name) is not None:
                    return component[name]
            return default

        def value_text(value: Any, default: str) -> str:
            if value is None or value == "":
                return default
            if isinstance(value, (int, float)):
                return f"{value:g}"
            return str(value).strip().replace("Ω", "ohm").replace("Ω", "ohm")

        lines = [
            f"* Voltforge SPICE Netlist - {board_type}",
            "* Auto-generated from canvas pin/wire topology",
            "",
        ]
        for index, component in enumerate(components):
            ctype = str(component.get("type", "")).upper()
            name = str(component.get("name", f"comp{index}"))
            prefix = "X"
            if ctype == "RESISTOR":
                prefix = "R"
                n1 = node_for(component, ("p1", "pin1", "positive", "1"))
                n2 = node_for(component, ("p2", "pin2", "negative", "2"), 1)
                lines.append(f"{prefix}{index + 1} {n1} {n2} {value_text(prop(component, 'resistance', 'value', default='1k'), '1k')}")
            elif "CAPACITOR" in ctype:
                prefix = "C"
                n1 = node_for(component, ("pos", "positive", "p1", "1"))
                n2 = node_for(component, ("neg", "negative", "p2", "2"), 1)
                lines.append(f"{prefix}{index + 1} {n1} {n2} {value_text(prop(component, 'capacitance', 'value', default='1uF'), '1uF')}")
            elif ctype == "INDUCTOR":
                n1 = node_for(component, ("p1", "positive", "1"))
                n2 = node_for(component, ("p2", "negative", "2"), 1)
                lines.append(f"L{index + 1} {n1} {n2} {value_text(prop(component, 'inductance', 'value', default='10mH'), '10mH')}")
            elif ctype == "TRANSFORMER":
                primary1 = node_for(component, ("primary1", "p1", "input1", "primary"))
                primary2 = node_for(component, ("primary2", "p2", "input2", "primary_return"), 1)
                secondary1 = node_for(component, ("secondary1", "s1", "output1", "secondary"), 2)
                secondary2 = node_for(component, ("secondary2", "s2", "output2", "secondary_return"), 3)
                primary_l = value_text(prop(component, "primaryInductance", "inductance", default="1H"), "1H")
                turns_ratio = float(prop(component, "turnsRatio", "ratio", default=1) or 1)
                secondary_l = value_text(prop(component, "secondaryInductance", default=f"{max(turns_ratio * turns_ratio, 1e-9):g}H"), "1H")
                lines.append(f"L{index + 1}P {primary1} {primary2} {primary_l}")
                lines.append(f"L{index + 1}S {secondary1} {secondary2} {secondary_l}")
                lines.append(f"K{index + 1} L{index + 1}P L{index + 1}S {value_text(prop(component, 'coupling', default=0.999), '0.999')}")
            elif "LED" in ctype or ctype in ("DIODE", "ZENER_DIODE", "SCHOTTKY_DIODE"):
                n1 = node_for(component, ("anode", "a", "positive", "1"))
                n2 = node_for(component, ("cathode", "k", "negative", "2"), 1)
                model = "DLED"
                if ctype == "ZENER_DIODE":
                    model = "DZENER"
                elif ctype == "SCHOTTKY_DIODE":
                    model = "DSCHOTTKY"
                lines.append(f"D{index + 1} {n1} {n2} {model}")
            elif ctype in ("NPN_TRANSISTOR", "PNP_TRANSISTOR"):
                collector = node_for(component, ("collector", "c"))
                base = node_for(component, ("base", "b"), 1)
                emitter = node_for(component, ("emitter", "e"), 2)
                lines.append(f"Q{index + 1} {collector} {base} {emitter} {'QPNP' if ctype == 'PNP_TRANSISTOR' else 'QNPN'}")
            elif ctype in ("NMOS", "PMOS"):
                drain = node_for(component, ("drain", "d"))
                gate = node_for(component, ("gate", "g"), 1)
                source = node_for(component, ("source", "s"), 2)
                lines.append(f"M{index + 1} {drain} {gate} {source} 0 {'QPMOS' if ctype == 'PMOS' else 'QNMOS'}")
            elif ctype in ("BATTERY_9V", "BATTERY_AA", "DC_SOURCE_3V3", "DC_SOURCE_5V", "DC_SOURCE_12V", "POWER_SUPPLY", "AC_FUNCTION_GENERATOR"):
                positive = node_for(component, ("positive", "pos", "plus", "vout", "vcc"))
                negative = node_for(component, ("negative", "neg", "minus", "gnd"), 1)
                defaults = {"BATTERY_9V": 9, "BATTERY_AA": 1.5, "DC_SOURCE_3V3": 3.3, "DC_SOURCE_5V": 5, "DC_SOURCE_12V": 12}
                voltage = prop(component, "voltage", "outputVoltage", default=defaults.get(ctype, v_supply))
                if ctype == "AC_FUNCTION_GENERATOR":
                    amplitude = value_text(prop(component, "amplitude", default=1), "1")
                    offset = value_text(prop(component, "offset", default=0), "0")
                    frequency = value_text(prop(component, "frequencyHz", "frequency", default=1000), "1000")
                    waveform = str(prop(component, "waveform", default="sine")).upper()
                    lines.append(f"V{index + 1} {positive} {negative} SIN({offset} {amplitude} {frequency})")
                else:
                    lines.append(f"V{index + 1} {positive} {negative} DC {value_text(voltage, str(defaults.get(ctype, v_supply)))}")
            elif ctype == "VOLTAGE_REGULATOR_7805":
                output = node_for(component, ("vout", "output", "5v"))
                ground = node_for(component, ("gnd", "ground"))
                lines.append(f"V{index + 1} {output} {ground} DC {value_text(prop(component, 'outputVoltage', 'voltage', default=5), '5')}")
            elif ctype == "GROUND":
                continue
            elif ctype in ("OPAMP_IDEAL", "OPAMP_LM358"):
                output = node_for(component, ("out", "output"))
                ground = node_for(component, ("gnd", "ground"))
                plus = node_for(component, ("in_plus", "plus", "non_inverting"))
                minus = node_for(component, ("in_minus", "minus", "inverting"), 1)
                gain = value_text(prop(component, "openLoopGain", default=100000), "100000")
                lines.append(f"E{index + 1} {output} {ground} {plus} {minus} {gain}")
            else:
                lines.append(f"* Unknown component: {name} ({ctype})")

        lines.extend([
            "",
            ".model DLED D(IS=1e-20 N=1.8 RS=5 BV=5)",
            ".model DZENER D(IS=1e-14 N=1.8 RS=4 BV=5.1 IBV=1m)",
            ".model DSCHOTTKY D(IS=1e-8 N=1.05 RS=0.2 BV=40)",
            ".model QNPN NPN(BF=200 IS=1e-14)",
            ".model QPNP PNP(BF=200 IS=1e-14)",
            ".model QNMOS NMOS(VTO=2 KP=0.01 RD=0.08 RS=0.08)",
            ".model QPMOS PMOS(VTO=-2 KP=0.01 RD=0.08 RS=0.08)",
            ".op",
            ".end",
        ])
        return "\n".join(lines)


class DCOperatingPointSolver:
    """Solves DC steady-state node voltages and branch currents for resistive networks."""

    @classmethod
    def solve_series_resistors(cls, v_supply: float, resistances: List[float]) -> Dict[str, Any]:
        r_total = sum(resistances)
        if r_total == 0:
            return {"error": "Total resistance cannot be zero (short circuit)."}
        i_total = v_supply / r_total
        node_voltages = []
        cumulative_drop = 0.0
        for r in resistances:
            v_drop = i_total * r
            cumulative_drop += v_drop
            node_voltages.append({
                "resistance": r,
                "voltageDrop": round(v_drop, 4),
                "nodeVoltage": round(v_supply - cumulative_drop, 4),
                "powerDissipation": round(i_total ** 2 * r, 6),
            })
        return {
            "vSupply": v_supply,
            "totalResistance": r_total,
            "totalCurrent_mA": round(i_total * 1000, 4),
            "nodeDetails": node_voltages,
        }

    @classmethod
    def solve_parallel_resistors(cls, v_supply: float, resistances: List[float]) -> Dict[str, Any]:
        if any(r == 0 for r in resistances):
            return {"error": "Resistance values cannot be zero (short circuit)."}
        r_parallel = 1.0 / sum(1.0 / r for r in resistances)
        i_total = v_supply / r_parallel
        branches = []
        for r in resistances:
            i_branch = v_supply / r
            branches.append({
                "resistance": r,
                "branchCurrent_mA": round(i_branch * 1000, 4),
                "powerDissipation": round(v_supply ** 2 / r, 6),
            })
        return {
            "vSupply": v_supply,
            "equivalentResistance": round(r_parallel, 4),
            "totalCurrent_mA": round(i_total * 1000, 4),
            "branches": branches,
        }


class TransientAnalysisSolver:
    """Simulates time-domain step responses for RC and RL circuits."""

    @classmethod
    def rc_charging(cls, v_supply: float, r: float, c: float, t: float) -> Dict[str, Any]:
        tau = r * c
        v_cap = v_supply * (1 - math.exp(-t / tau))
        i_current = (v_supply / r) * math.exp(-t / tau)
        return {
            "timeConstant_s": round(tau, 6),
            "capacitorVoltage_V": round(v_cap, 4),
            "chargingCurrent_mA": round(i_current * 1000, 4),
            "percentCharged": round((v_cap / v_supply) * 100, 2),
            "time5Tau_s": round(5 * tau, 6),
        }

    @classmethod
    def rl_step_response(cls, v_supply: float, r: float, l: float, t: float) -> Dict[str, Any]:
        tau = l / r
        i_current = (v_supply / r) * (1 - math.exp(-t / tau))
        v_inductor = v_supply * math.exp(-t / tau)
        return {
            "timeConstant_s": round(tau, 6),
            "inductorCurrent_mA": round(i_current * 1000, 4),
            "inductorVoltage_V": round(v_inductor, 4),
            "steadyStateCurrent_mA": round((v_supply / r) * 1000, 4),
        }


class ACFrequencyResponseSolver:
    """Generates Bode plot data (magnitude & phase) for passive RC/RL/LC filters."""

    @classmethod
    def rc_lowpass_bode(cls, r: float, c: float, freq_points: int = 50) -> Dict[str, Any]:
        f_cutoff = 1.0 / (2.0 * math.pi * r * c)
        freqs = [10 ** (i * 6.0 / freq_points) for i in range(freq_points)]
        bode_data = []
        for f in freqs:
            omega = 2 * math.pi * f
            magnitude = 1.0 / math.sqrt(1.0 + (omega * r * c) ** 2)
            gain_db = 20 * math.log10(magnitude) if magnitude > 0 else -120
            phase_deg = -math.degrees(math.atan(omega * r * c))
            bode_data.append({
                "frequency_Hz": round(f, 2),
                "gain_dB": round(gain_db, 2),
                "phase_deg": round(phase_deg, 2),
            })
        return {
            "filterType": "RC Low-Pass",
            "cutoffFrequency_Hz": round(f_cutoff, 2),
            "resistance": r,
            "capacitance": c,
            "bodeData": bode_data,
        }

    @classmethod
    def lc_resonant_frequency(cls, l: float, c: float) -> Dict[str, Any]:
        f_resonant = 1.0 / (2.0 * math.pi * math.sqrt(l * c))
        return {
            "inductance_H": l,
            "capacitance_F": c,
            "resonantFrequency_Hz": round(f_resonant, 2),
        }


class PWMDutyCycleCalculator:
    """Calculates average output voltage from PWM duty cycle."""

    @classmethod
    def calculate(cls, v_peak: float, duty_cycle_percent: float) -> Dict[str, Any]:
        duty = duty_cycle_percent / 100.0
        v_avg = duty * v_peak
        return {
            "vPeak": v_peak,
            "dutyCyclePercent": duty_cycle_percent,
            "vAverage": round(v_avg, 4),
            "rmsVoltage": round(v_peak * math.sqrt(duty), 4),
        }


class Timer555Solver:
    """Solves 555 timer astable oscillator frequency and duty cycle."""

    @classmethod
    def astable(cls, r1: float, r2: float, c: float) -> Dict[str, Any]:
        t_high = 0.693 * (r1 + r2) * c
        t_low = 0.693 * r2 * c
        period = t_high + t_low
        frequency = 1.0 / period if period > 0 else 0
        duty_cycle = (t_high / period) * 100 if period > 0 else 0
        return {
            "r1": r1,
            "r2": r2,
            "capacitance": c,
            "frequency_Hz": round(frequency, 4),
            "period_s": round(period, 6),
            "dutyCyclePercent": round(duty_cycle, 2),
            "tHigh_s": round(t_high, 6),
            "tLow_s": round(t_low, 6),
        }


if __name__ == "__main__":
    # Test SPICE netlist export
    netlist = SpiceNetlistExporter.export_netlist(
        [{"type": "RESISTOR", "value": "1k"}, {"type": "LED"}, {"type": "RESISTOR", "value": "220"}],
        [],
        "ARDUINO_UNO",
        5.0
    )
    print("=== SPICE Netlist ===")
    print(netlist)

    # Test DC Operating Point
    dc = DCOperatingPointSolver.solve_series_resistors(5.0, [220, 330, 470])
    print("\n=== DC Operating Point (Series) ===")
    import json
    print(json.dumps(dc, indent=2))

    # Test RC Transient
    rc = TransientAnalysisSolver.rc_charging(5.0, 10000, 100e-6, 0.5)
    print("\n=== RC Charging at t=0.5s ===")
    print(json.dumps(rc, indent=2))

    # Test 555 Timer
    t555 = Timer555Solver.astable(10000, 47000, 10e-6)
    print("\n=== 555 Timer Astable ===")
    print(json.dumps(t555, indent=2))
