"""
Voltforge AI - SPICE Netlist & Analog Circuit Simulation Engine
Covers Features 101-110: DC Operating Point, Transient Analysis, AC Response,
Modified Nodal Analysis (MNA), LED I-V curves, PWM Integration, Power Loss Analysis.
"""

import math
import logging
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("voltforge-ai.spice")


class SpiceNetlistExporter:
    """Converts Voltforge canvas components and wires into standard SPICE (.cir) netlists."""

    COMPONENT_SPICE_MAP = {
        "RESISTOR": "R",
        "CAPACITOR": "C",
        "INDUCTOR": "L",
        "LED": "D",
        "DIODE": "D",
        "NPN_TRANSISTOR": "Q",
        "PNP_TRANSISTOR": "Q",
        "NMOS": "M",
        "PMOS": "M",
    }

    @classmethod
    def export_netlist(
        cls,
        components: List[Dict[str, Any]],
        wires: List[Dict[str, Any]],
        board_type: str = "ARDUINO_UNO",
        v_supply: float = 5.0,
    ) -> str:
        lines = [
            f"* Voltforge SPICE Netlist — {board_type}",
            f"* Auto-generated by Voltforge AI SPICE Engine",
            f"",
            f"Vsupply VCC 0 DC {v_supply}",
        ]

        node_counter = 1
        for idx, comp in enumerate(components):
            ctype = comp.get("type", "").upper()
            cname = comp.get("name", f"comp{idx}")
            value = comp.get("value", "1k")
            prefix = cls.COMPONENT_SPICE_MAP.get(ctype, "X")
            spice_name = f"{prefix}{idx + 1}"

            if ctype == "RESISTOR":
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} {value}")
                node_counter += 2
            elif ctype == "CAPACITOR":
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} {value}")
                node_counter += 2
            elif ctype in ("LED", "DIODE"):
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} DLED")
                node_counter += 2
            elif ctype in ("NPN_TRANSISTOR",):
                lines.append(f"{spice_name} N{node_counter} N{node_counter + 1} N{node_counter + 2} Q2N2222")
                node_counter += 3
            else:
                lines.append(f"* Unknown component: {cname} ({ctype})")

        lines.append("")
        lines.append(".model DLED D(IS=1e-20 N=1.8 RS=5 BV=5)")
        lines.append(".model Q2N2222 NPN(BF=200 IS=1e-14)")
        lines.append("")
        lines.append(".op")
        lines.append(".end")

        return "\n".join(lines)


class DCOperatingPointSolver:
    """Solves DC steady-state node voltages and branch currents for resistive networks."""

    @classmethod
    def solve_series_resistors(cls, v_supply: float, resistances: List[float]) -> Dict[str, Any]:
        r_total = sum(resistances)
        if r_total == 0:
            return {"error": "Total resistance cannot be zero (short circuit)."}
        i_total = v_supply / r_total
        node_voltages = []
        cumulative_drop = 0.0
        for r in resistances:
            v_drop = i_total * r
            cumulative_drop += v_drop
            node_voltages.append({
                "resistance": r,
                "voltageDrop": round(v_drop, 4),
                "nodeVoltage": round(v_supply - cumulative_drop, 4),
                "powerDissipation": round(i_total ** 2 * r, 6),
            })
        return {
            "vSupply": v_supply,
            "totalResistance": r_total,
            "totalCurrent_mA": round(i_total * 1000, 4),
            "nodeDetails": node_voltages,
        }

    @classmethod
    def solve_parallel_resistors(cls, v_supply: float, resistances: List[float]) -> Dict[str, Any]:
        if any(r == 0 for r in resistances):
            return {"error": "Resistance values cannot be zero (short circuit)."}
        r_parallel = 1.0 / sum(1.0 / r for r in resistances)
        i_total = v_supply / r_parallel
        branches = []
        for r in resistances:
            i_branch = v_supply / r
            branches.append({
                "resistance": r,
                "branchCurrent_mA": round(i_branch * 1000, 4),
                "powerDissipation": round(v_supply ** 2 / r, 6),
            })
        return {
            "vSupply": v_supply,
            "equivalentResistance": round(r_parallel, 4),
            "totalCurrent_mA": round(i_total * 1000, 4),
            "branches": branches,
        }


class TransientAnalysisSolver:
    """Simulates time-domain step responses for RC and RL circuits."""

    @classmethod
    def rc_charging(cls, v_supply: float, r: float, c: float, t: float) -> Dict[str, Any]:
        tau = r * c
        v_cap = v_supply * (1 - math.exp(-t / tau))
        i_current = (v_supply / r) * math.exp(-t / tau)
        return {
            "timeConstant_s": round(tau, 6),
            "capacitorVoltage_V": round(v_cap, 4),
            "chargingCurrent_mA": round(i_current * 1000, 4),
            "percentCharged": round((v_cap / v_supply) * 100, 2),
            "time5Tau_s": round(5 * tau, 6),
        }

    @classmethod
    def rl_step_response(cls, v_supply: float, r: float, l: float, t: float) -> Dict[str, Any]:
        tau = l / r
        i_current = (v_supply / r) * (1 - math.exp(-t / tau))
        v_inductor = v_supply * math.exp(-t / tau)
        return {
            "timeConstant_s": round(tau, 6),
            "inductorCurrent_mA": round(i_current * 1000, 4),
            "inductorVoltage_V": round(v_inductor, 4),
            "steadyStateCurrent_mA": round((v_supply / r) * 1000, 4),
        }


class ACFrequencyResponseSolver:
    """Generates Bode plot data (magnitude & phase) for passive RC/RL/LC filters."""

    @classmethod
    def rc_lowpass_bode(cls, r: float, c: float, freq_points: int = 50) -> Dict[str, Any]:
        f_cutoff = 1.0 / (2.0 * math.pi * r * c)
        freqs = [10 ** (i * 6.0 / freq_points) for i in range(freq_points)]
        bode_data = []
        for f in freqs:
            omega = 2 * math.pi * f
            magnitude = 1.0 / math.sqrt(1.0 + (omega * r * c) ** 2)
            gain_db = 20 * math.log10(magnitude) if magnitude > 0 else -120
            phase_deg = -math.degrees(math.atan(omega * r * c))
            bode_data.append({
                "frequency_Hz": round(f, 2),
                "gain_dB": round(gain_db, 2),
                "phase_deg": round(phase_deg, 2),
            })
        return {
            "filterType": "RC Low-Pass",
            "cutoffFrequency_Hz": round(f_cutoff, 2),
            "resistance": r,
            "capacitance": c,
            "bodeData": bode_data,
        }

    @classmethod
    def lc_resonant_frequency(cls, l: float, c: float) -> Dict[str, Any]:
        f_resonant = 1.0 / (2.0 * math.pi * math.sqrt(l * c))
        return {
            "inductance_H": l,
            "capacitance_F": c,
            "resonantFrequency_Hz": round(f_resonant, 2),
        }


class PWMDutyCycleCalculator:
    """Calculates average output voltage from PWM duty cycle."""

    @classmethod
    def calculate(cls, v_peak: float, duty_cycle_percent: float) -> Dict[str, Any]:
        duty = duty_cycle_percent / 100.0
        v_avg = duty * v_peak
        return {
            "vPeak": v_peak,
            "dutyCyclePercent": duty_cycle_percent,
            "vAverage": round(v_avg, 4),
            "rmsVoltage": round(v_peak * math.sqrt(duty), 4),
        }


class Timer555Solver:
    """Solves 555 timer astable oscillator frequency and duty cycle."""

    @classmethod
    def astable(cls, r1: float, r2: float, c: float) -> Dict[str, Any]:
        t_high = 0.693 * (r1 + r2) * c
        t_low = 0.693 * r2 * c
        period = t_high + t_low
        frequency = 1.0 / period if period > 0 else 0
        duty_cycle = (t_high / period) * 100 if period > 0 else 0
        return {
            "r1": r1,
            "r2": r2,
            "capacitance": c,
            "frequency_Hz": round(frequency, 4),
            "period_s": round(period, 6),
            "dutyCyclePercent": round(duty_cycle, 2),
            "tHigh_s": round(t_high, 6),
            "tLow_s": round(t_low, 6),
        }


if __name__ == "__main__":
    # Test SPICE netlist export
    netlist = SpiceNetlistExporter.export_netlist(
        [{"type": "RESISTOR", "value": "1k"}, {"type": "LED"}, {"type": "RESISTOR", "value": "220"}],
        [],
        "ARDUINO_UNO",
        5.0
    )
    print("=== SPICE Netlist ===")
    print(netlist)

    # Test DC Operating Point
    dc = DCOperatingPointSolver.solve_series_resistors(5.0, [220, 330, 470])
    print("\n=== DC Operating Point (Series) ===")
    import json
    print(json.dumps(dc, indent=2))

    # Test RC Transient
    rc = TransientAnalysisSolver.rc_charging(5.0, 10000, 100e-6, 0.5)
    print("\n=== RC Charging at t=0.5s ===")
    print(json.dumps(rc, indent=2))

    # Test 555 Timer
    t555 = Timer555Solver.astable(10000, 47000, 10e-6)
    print("\n=== 555 Timer Astable ===")
    print(json.dumps(t555, indent=2))
