"""Bind family partitions to immutable ingestion and every protected evaluation input."""
from collections import Counter
import base64
import json
from pathlib import Path
import tempfile

from data_governance.ingestion import pipeline as ingestion
from data_governance.foundation import inventory
from evaluation import leakage as legacy
from evaluation.foundation import suite
from .signatures import canonical, sha, content_segments, features, compare
from .partition import ROOT, POLICY, lineage_keys, plan_partitions

AI = ROOT.parents[1]
INPUT = AI / "corpus/ingestion/v1/4eb23ca6950fb9d7fa9fd87bfbfcbe29aadd92d008a1d9d1e45229231078948d"
FIXTURE_INPUT = AI / "corpus/extraction-fixtures/v1/34b8ea2db7081e29c315d69da02f0b2814682866a59d1f58a5ce98e2fb6833ca"
SOURCES = ("__init__.py", "policy.v1.json", "signatures.py", "partition.py", "release.py")


def entries(release, kind):
    manifest = ingestion.read_json(release / "manifest.json")
    for entry in manifest["files"]:
        if entry["kind"] == kind:
            with (release / entry["path"]).open(encoding="utf-8") as stream:
                for line in stream:
                    yield json.loads(line)


def legacy_lineage(record):
    """Conservative sidecar for old generated bytes, never a provenance rewrite."""
    task = record["task"]
    context = record["input"]["projectContext"]
    payload = context["payload"]
    if task == "firmware_generation":
        family = "firmware:" + payload["templateId"]
    elif task == "compiler_repair":
        # Both existing repair recipes fix the same status-LED program. Code
        # signatures also connect their corrected program to any copied variant.
        family = "firmware:status-led-repair"
    elif task in {"circuit_validation", "structured_output", "wiring"}:
        family = "circuit:i2c-oled"
    else:
        family = "task:" + task
    return {"kind": "owned-synthetic", "sourceFamilyId": "owned-generator-recipe:" + family,
            "documentFamilyId": context["sourceProjectRevision"], "repositoryId": "Voltforge_AI/synthetic_data",
            "templateFamilyId": family, "circuitFamilyId": family if family.startswith("circuit:") else None,
            "scenarioFamilyId": family, "boardVariant": context.get("boardType"),
            "derivation": "Conservative legacy sidecar from verified task/context keys; older generator had no pre-render split reservation."}


def document(record, raw, normalized, document_id):
    text = inventory.payload_text(record)
    return {"id": document_id, "recordId": record["recordId"], "lineage": legacy_lineage(record),
            "rawSha256": sha(raw), "normalizedSha256": sha(normalized), "features": features(content_segments({"input": record["input"], "output": record["output"]})),
            "text": text}


def load_inputs():
    # Rebuild equality prevents edited staging labels/checksums from becoming a
    # source or training permission. Evaluation material is guard input only.
    ingestion.verify(INPUT, recompute=True)
    raw_records = {row["documentId"]: row for row in entries(INPUT, "raw")}
    documents, normalized = [], {}
    for row in entries(INPUT, "normalized"):
        raw = base64.b64decode(raw_records[row["documentId"]]["rawBase64"], validate=True)
        record = json.loads(raw)
        if row["text"] != inventory.payload_text(record) or sha(raw) != row["lineage"]["rawSha256"]:
            raise ValueError("Ingestion record/raw lineage mismatch")
        documents.append(document(record, raw, row["text"], row["documentId"]))
        normalized[row["documentId"]] = row
    return documents, normalized


def protected_registry():
    from synthetic_data.immutable_release import verify_all_releases
    suite.verify_suite()
    legacy.verify_frozen_suite()
    inventory.verify()
    ingestion.verify(FIXTURE_INPUT, recompute=True)
    guards, paths = [], {INPUT / "manifest.json", suite.ROOT / "manifest.v1.json", legacy.MANIFEST_PATH,
                         inventory.ROOT / "manifest.v1.json", ingestion.FIXTURES / "catalog.json", FIXTURE_INPUT / "manifest.json"}
    extracted_fixtures = {row["lineage"]["rawSha256"]: row["text"] for row in entries(FIXTURE_INPUT, "normalized")}
    paths.update(FIXTURE_INPUT / row["path"] for row in ingestion.read_json(FIXTURE_INPUT / "manifest.json")["files"])
    for split in suite.SPLITS:
        path = suite.ROOT / f"fixtures/v1/{split}.jsonl"
        paths.add(path)
        for line in path.read_text(encoding="utf-8").splitlines():
            case = json.loads(line)
            keys = {key + ":" + case[key] for key in ("templateFamilyId", "scenarioFamilyId")}
            keys.add("source:" + case["sourceFamilyId"])
            guards.append({"id": "foundation:" + case["id"], "keys": sorted(keys), "features": features(content_segments(
                {"scenario": case["scenarioText"], "prompt": case["prompt"], "turns": case["turns"], "context": case["context"], "oracle": case["oracle"]})),
                "kind": "frozen-foundation-evaluation"})
    paths.add(legacy.FIXTURE_PATH)
    for case in legacy.load_cases():
        guards.append({"id": "legacy-evaluation:" + case["id"], "keys": [],
                       "features": features(legacy.protected_texts(case)), "kind": "frozen-gen1-evaluation"})
    heldout_ids = set()
    for path in sorted((AI / "model/tokenizers").glob("*/tokenizer_manifest.json")):
        paths.add(path)
        heldout_ids.update(ingestion.read_json(path)["lineage"]["split"]["evaluationRecordIds"])
    recovered = set()
    for release in verify_all_releases():
        manifest_path = AI / release["releasePath"] / "manifest.json"
        if manifest_path.exists():
            paths.add(manifest_path)
        for shard in release["manifest"]["shards"]:
            path = AI / release["releasePath"] / "content" / shard["sourcePath"]
            paths.add(path)
            for line in path.read_bytes().splitlines(keepends=True):
                record = json.loads(line)
                if record["recordId"] not in heldout_ids:
                    continue
                identity = "historical-heldout:" + record["recordId"] + ":" + sha(line)
                if identity in recovered:
                    continue
                recovered.add(identity)
                item = document(record, line, inventory.payload_text(record), identity)
                guards.append({key: item[key] for key in ("id", "recordId", "rawSha256", "normalizedSha256", "features")} | {
                    "keys": sorted(lineage_keys(item["lineage"])), "kind": "historical-tokenizer-heldout"})
    for identity in sorted(heldout_ids):
        guards.append({"id": "historical-id:" + identity, "recordId": identity, "keys": [], "features": features([]), "kind": "historical-id-denial"})
    # Parser regression material is also evaluation-only. Never count it as new
    # source data or emit its text into the partition artifacts.
    for row in ingestion.read_json(ingestion.FIXTURES / "catalog.json")["files"]:
        path = inventory.safe_path(row["path"], ingestion.FIXTURES)
        paths.add(path)
        if inventory.file_hash(path) != row["sha256"]:
            raise ValueError("Extraction fixture changed")
        text = path.read_bytes().decode("utf-8", errors="replace") if row["mediaType"] != "application/pdf" else ""
        guards.append({"id": "extraction-fixture:" + row["sha256"], "rawSha256": row["sha256"], "keys": ["source:vf-ingestion-test-fixtures-only"],
                       "features": features([text, extracted_fixtures.get(row["sha256"], "")]), "kind": "extraction-regression-only"})
    # The complete tokenizer release is bound; proxy counts are not Gen2 tokens.
    paths.update(path for path in (AI / POLICY["proxyTokenizer"]).iterdir() if path.is_file())
    guards.sort(key=lambda row: row["id"])
    material = [{key: value for key, value in row.items() if key != "features"} | {
        "features": {key: sorted([sorted(x) for x in value]) if key == "text" else sorted(value) for key, value in row["features"].items()}}
        for row in guards]
    return guards, {"count": len(guards), "kindCounts": dict(Counter(row["kind"] for row in guards)), "sha256": sha(canonical(material)),
                    "inputs": [{"path": path.relative_to(AI).as_posix(), "sha256": inventory.file_hash(path)} for path in sorted(paths)]}


def cross_split_audit(documents, decisions, guards):
    included = {row["documentId"]: row["split"] for row in decisions if row["split"] != "quarantine"}
    docs = [row for row in documents if row["id"] in included]
    counts = Counter({"lineage": 0, "exactRaw": 0, "exactNormalized": 0, "nearTextOrCode": 0, "protected": 0})
    for i, left in enumerate(docs):
        for right in docs[i + 1:]:
            if included[left["id"]] == included[right["id"]]:
                continue
            counts["lineage"] += bool(lineage_keys(left["lineage"]) & lineage_keys(right["lineage"]))
            counts["exactRaw"] += left["rawSha256"] == right["rawSha256"]
            counts["exactNormalized"] += left["normalizedSha256"] == right["normalizedSha256"]
            counts["nearTextOrCode"] += compare(left["features"], right["features"], POLICY) is not None
        for guard in guards:
            if (left.get("recordId") is not None and left.get("recordId") == guard.get("recordId")
                or left.get("rawSha256") is not None and left.get("rawSha256") == guard.get("rawSha256")
                or left.get("normalizedSha256") is not None and left.get("normalizedSha256") == guard.get("normalizedSha256")
                or lineage_keys(left["lineage"]) & set(guard.get("keys", ()))
                or compare(left["features"], guard["features"], POLICY, protected=True)):
                counts["protected"] += 1
                break
    if any(counts.values()):
        raise ValueError("Cross-split or protected content collision")
    return {"status": "passed", "counts": dict(counts), "includedDocuments": len(docs),
            "nonemptySplits": sorted(set(included.values())), "semanticCompletenessClaimed": False}


def exposure_accounting(unique_by_split, passes):
    if type(passes) is not int or not 1 <= passes <= 10 or any(type(v) is not int or v < 0 for v in unique_by_split.values()):
        raise ValueError("Invalid token/exposure accounting")
    return {"uniqueAcceptedDocumentProxyTokens": unique_by_split, "hypotheticalPasses": passes,
            "hypotheticalTrainingExposures": unique_by_split.get("train", 0) * passes,
            "observedTrainingExposures": 0, "gen2ReleasedTrainingTokens": 0,
            "repetitionAddsUniqueData": False, "trainingAllowed": False}


def compute():
    from model.tokenizer import VoltForgeTokenizer
    docs, normalized = load_inputs()
    guards, registry = protected_registry()
    result = plan_partitions(docs, guards)
    audit = cross_split_audit(docs, result["assignments"], guards)
    tokenizer = VoltForgeTokenizer()
    tokenizer.load(AI / POLICY["proxyTokenizer"])
    tokens = {row["id"]: len(tokenizer.encode(row["text"])) for row in docs}
    accepted_tokens = {split: sum(tokens[row["documentId"]] for row in result["assignments"] if row["split"] == split)
                       for split in ("train", "validation", "test")}
    plan = {"schemaVersion": 1, "policy": POLICY, "ingestionManifestSha256": inventory.file_hash(INPUT / "manifest.json"),
            "guards": registry, "sources": [{"path": name, "sha256": inventory.file_hash(ROOT / name)} for name in SOURCES],
            "trainingAllowed": False}
    scorecard = {"inputDocuments": len(docs), "splitCounts": {split: result["splitCounts"].get(split, 0) for split in ("train", "validation", "test", "quarantine")},
                 "componentCount": len(result["components"]), "protectedComponentCount": sum(row["protected"] for row in result["components"]),
                 "reasonCounts": result["reasonCounts"], "directProtectedMatches": len(result["protectedMatches"]),
                 "duplicateEdges": len(result["duplicateMatches"]), "crossSplitAudit": audit,
                 "inputEligibleProxyTokens": sum(tokens.values()), "proxyTokenizerVersion": "1.1.0",
                 "exposureAccounting": [exposure_accounting(accepted_tokens, passes) for passes in (1, 3, 10)],
                 "trainingPoolAvailable": result["splitCounts"].get("train", 0) > 0,
                 "allThreePartitionsPopulated": all(result["splitCounts"].get(split, 0) > 0 for split in ("train", "validation", "test")),
                 "semanticCompletenessClaimed": False, "trainingAllowed": False}
    blobs = {}
    for split in ("train", "validation", "test"):
        rows = [{**normalized[row["documentId"]], "partition": {"split": split, "componentId": row["componentId"], "seed": POLICY["seed"]}}
                for row in result["assignments"] if row["split"] == split]
        blobs[split + ".jsonl"] = "".join(canonical(row) + "\n" for row in rows).encode()
    for name, value in (("decisions.jsonl", result["assignments"]), ("components.jsonl", result["components"]),
                        ("protected-matches.jsonl", result["protectedMatches"]), ("duplicate-matches.jsonl", result["duplicateMatches"])):
        blobs[name] = "".join(canonical(row) + "\n" for row in value).encode()
    blobs["scorecard.json"] = (canonical(scorecard) + "\n").encode()
    manifest = {"schemaVersion": 1, "releaseId": sha(canonical(plan)), "plan": plan, "status": "immutable-partition-candidates",
                "trainingAllowed": False, "gen2CorpusReleased": False, "networkAccessed": False,
                "files": [{"path": name, "sha256": sha(data), "bytes": len(data)} for name, data in sorted(blobs.items())],
                "limits": ["Current legacy recipes did not reserve partitions before rendering; their conservative sidecar protects entire connected families.",
                           "Lexical/structural checks are tested, not a proof against arbitrary semantic paraphrases or unknown historical bytes.",
                           "Zero collision counts with empty partitions are not data adequacy; consult nonemptySplits and trainingPoolAvailable.",
                           "Protected acceptance content has checksum integrity but still requires separate confidential custody before training.",
                           "New corpus sources require a new ingestion/partition release; Gen2 corpus/model release gates remain open."]}
    return manifest, blobs, scorecard


def build(output_root=AI / "corpus/partitions/v1"):
    manifest, blobs, scorecard = compute()
    path = Path(output_root) / manifest["releaseId"]
    with ingestion.build_lock(AI / "corpus/.work" / ("partition-" + manifest["releaseId"] + ".lock")):
        if (path / "manifest.json").exists():
            return verify(path, recompute=True)
        path.mkdir(parents=True, exist_ok=True)
        for name, data in blobs.items():
            ingestion.write_immutable(path / name, data)
        ingestion.write_immutable(path / "manifest.json", (canonical(manifest) + "\n").encode())
    return {"status": "passed", "releasePath": str(path), "manifestSha256": inventory.file_hash(path / "manifest.json"), "scorecard": scorecard}


def verify(path, *, recompute=False):
    path = Path(path)
    manifest = ingestion.read_json(path / "manifest.json")
    if manifest["releaseId"] != path.name or sha(canonical(manifest["plan"])) != path.name or manifest["trainingAllowed"] is not False or manifest["gen2CorpusReleased"] is not False:
        raise ValueError("Invalid partition release identity or use claim")
    if manifest["plan"]["policy"] != POLICY or len(manifest["plan"]["sources"]) != len(SOURCES) or {row["path"] for row in manifest["plan"]["sources"]} != set(SOURCES):
        raise ValueError("Partition policy or source set changed")
    for row in manifest["plan"]["sources"]:
        if inventory.file_hash(inventory.safe_path(row["path"], ROOT)) != row["sha256"]:
            raise ValueError("Partition implementation changed")
    for row in manifest["plan"]["guards"]["inputs"]:
        if inventory.file_hash(inventory.safe_path(row["path"], AI)) != row["sha256"]:
            raise ValueError("Protected input checksum mismatch")
    if inventory.file_hash(INPUT / "manifest.json") != manifest["plan"]["ingestionManifestSha256"]:
        raise ValueError("Ingestion binding changed")
    expected = {"manifest.json"}
    for row in manifest["files"]:
        if row["path"] in expected:
            raise ValueError("Duplicate release file")
        expected.add(row["path"])
        target = inventory.safe_path(row["path"], path)
        if target.stat().st_size != row["bytes"] or inventory.file_hash(target) != row["sha256"]:
            raise ValueError("Partition shard checksum mismatch")
    if {item.name for item in path.iterdir() if not item.name.startswith(".pending-")} != expected:
        raise ValueError("Unexpected partition file")
    if recompute:
        current, blobs, _ = compute()
        if current != manifest or any((path / name).read_bytes() != data for name, data in blobs.items()):
            raise ValueError("Partition output is not reproducible")
    return {"status": "passed", "releasePath": str(path), "manifestSha256": inventory.file_hash(path / "manifest.json"),
            "recomputed": recompute, "scorecard": ingestion.read_json(path / "scorecard.json"), "trainingAllowed": False}


def require_partition_use(path, split, usage):
    verify(path, recompute=True)
    if usage in POLICY["excludedUses"]:
        # Task 023 must add a reviewed corpus release/usage grant, never infer it
        # from a filename containing 'train' or relabel this staging manifest.
        raise ValueError("TRAINING_CORPUS_RELEASE_REQUIRED")
    if usage != "partition-review" or split not in {"train", "validation", "test"}:
        raise ValueError("PARTITION_USE_DENIED")
    return {"path": str(Path(path) / (split + ".jsonl")), "usage": usage, "trainingAllowed": False}
